spring:
  #本地数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CST&useSSL=false #url
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456